name: Bug
description: Simple bug report for labyrinth_game
title: "[bug] <short summary>"
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What is the bug?
      description: Explain in simple words what is wrong.
      placeholder: |
        Example:
        - I did: ...
        - I expected: ...
        - I saw: ...
    validations:
      required: true

  - type: input
    id: task_id
    attributes:
      label: Task ID in project (if any)
      placeholder: "TASK-123 or issue #"
