name: Feature
description: Simple feature request for labyrinth_game
title: "[feature] <short summary>"
labels: ["feature"]
body:
  - type: textarea
    id: description
    attributes:
      label: What should we add or change?
      description: Describe the idea in simple words.
      placeholder: |
        Example:
        - What you want: ...
        - Why it is useful: ...
    validations:
      required: true

  - type: input
    id: task_id
    attributes:
      label: Task ID in project (if any)
      placeholder: "TASK-123 or issue #"
